spring:
  application:
    name: my-project
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:my-project
    username: anil
    password: anil
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update